Add egs_dynamic_geometry and egs_view time viewing
nrc-cnrc/EGSnrc pull request #1022
Opened 2023-06-22 15:31 UTC by a-l-demelo

Add the ability for dynamic geometries, including translation and rotation of any geometry. This is similar to `egs_dynamic_source`. Time indices are synchronized with any source that includes time indexes such as `egs_beam_source`, `IAEAphsp_source`, and `egs_dynamic_source`. 

Add a time slider to `egs_view` that shows geometry motion. Includes a time window for showing tracks over a window of time, and the tracks update as you move the time index slider to show tracks synchronized with geometry motion.

2024-01-24 14:54 UTC, rtownson approved these changes

2024-06-13 23:06 UTC, blakewalters commented
This is excellent!  I tested out dynamic motion of a fairly complex rotating geometry within a stationary one (I also threw in some translation for good measure), and I was able to display the track evolution in egs_view beautifully.  I would just clarify the documentation at the top of the egs_dynamic_geometry.h a bit by:
1) changing the notation for the translation from "x(N) y(N) z(N)" to "xtransl(N) ytransl(N) ztransl(N)"
2) indicating that rotations are defined in degrees and translations in cm.
Otherwise, let's get this merged forthwith!

2024-08-09 22:50 UTC, ftessier requested changes
### Synchronized .ptracks file

I wonder why a `.syncptracks` extension is added to distinguish static and dynamic tracks files. I think we ought to avoid adding extensions where possible. I would keep `.ptracks` for all tracks file, and simply add a `0` time to files that do not track time. If the purpose of a new extension is to curb file size or address backward compatility, then this ought to be handled by a flag _inside_ the file (or otherwise determined from the file content), not in the file extension!

### Time instead of monitor units

The language (text, variables, functions) were changed from `mu` to `time`, which is great for clarity (`mu` lingo is specific to medical physics). However, there subsists a few instances of `mu` in `egs_phsp_scoring`. If that is not required for some other reason, I suggest updating those as well:

```c
HEN_HOUSE/egs++/ausgab_objects/egs_phsp_scoring/egs_phsp_scoring.h
80:IAEA format: iq,E,[x],[y],[z],u,v,wt,latch,[mu]
85:user has the option of scoring the synchronization parameter, mu, passed from the source.
100:          score mu                 = yes or no [default] (IAEA format only)
127:In IAEA-format phase space files, the user can opt to score the synchronization parameter, mu.
131:synchronized CMs or scored using this ausgab object with mu scoring turned on) and
215:        score mu = no
451:        EGS_Float E, x, y, z, u, v, w, wt, mu;
493:    int mu_ind; //IAEA id for mu--no ID for now so set to generic float (0)
501:    bool score_mu; //set to true if scoring mu
502:    float pmu; //mu value associated with particle

HEN_HOUSE/egs++/ausgab_objects/egs_phsp_scoring/egs_phsp_scoring.cpp
159:            iaea_i_mu=0; //position of mu in array
188:        description += "\n mu will be scored (if available)";
244:    //if user requested mu scoring, check if mu is available
246:        egsWarning("\nEGS_PhspScoring: User requested mu scoring, but mu is inavailable with this source.\n");
247:        egsWarning("Turning off mu scoring.\n");
281:        p_stack[phsp_index].mu = app->getTimeIndex();
406:                iaea_extra_float[iaea_i_mu] = p_stack[j].mu;
633:                //see if user wants to score mu (if available)
635:                if (!input->getInput("score mu", str)) {
639:                    imuscore = input->getInput("score mu",allowed_muscore,-1);
641:                        egsWarning("\nEGS_PhspScoring: Invalid input for mu scoring.  Will not score mu.\n");
```

### Minor comments

- [x] Resolve all conversations left as individual comments.

2024-08-09 22:50 UTC, ftessier commented on HEN_HOUSE/egs++/egs_transformations.cpp
> +    else {       //egsWarning("getTransformation: rotation specified by 3 angles: %g   %g   %g\n\n",tmp[0],tmp[1],tmp[2]);
Remove spurious debug output that is commented out.

2024-08-09 22:50 UTC, ftessier commented on HEN_HOUSE/egs++/egs_transformations.cpp
> +     * through the control points and the sampled mu value. The sampled transformation coordinates are passed here to build a transformation */
Change `mu value` to `time value`

2024-08-09 22:50 UTC, ftessier commented on HEN_HOUSE/egs++/view/image_window.cpp
> +}
Add newline at end of file

2024-08-09 22:50 UTC, ftessier commented on HEN_HOUSE/egs++/view/viewcontrol.cpp
> +#include<unistd.h>
Add space after `#include`

2024-08-09 22:50 UTC, ftessier commented on HEN_HOUSE/egs++/view/viewcontrol.cpp
> +        geometryNames.clear(); // adding this to solve loading new input file from file tab in egsview. Previously name array is never cleared after loading new input file
🎉

2024-08-09 22:50 UTC, ftessier commented on HEN_HOUSE/egs++/geometry/egs_dynamic_geometry/egs_dynamic_geometry.cpp
> +#  Author:          Alex Demelo, 2023
Should be `Alexandre Demelo`, for consistency with other files.

2024-08-09 22:50 UTC, ftessier commented on HEN_HOUSE/egs++/geometry/egs_dynamic_geometry/egs_dynamic_geometry.h
> +#  Author:          Alex Demelo 2023
Should be `Alexandre Demelo`, for consistency with other files.

2024-08-09 22:52 UTC, ftessier commented
@a-l-demelo if you have please comment on the review comments. In the meantime I will address the minor issues.

2024-08-09 22:59 UTC, ftessier commented on HEN_HOUSE/egs++/egs_base_geometry.h
> +     *1) it is re implemented in any composite geometry, where it will call next geom on all of its components
Should be `reimplemented` (no hyphen, see [discussion](https://english.stackexchange.com/questions/310040/reimplement-or-re-implement)).

2024-08-16 16:18 UTC, blakewalters approved these changes

2024-09-03 20:11 UTC, rtownson commented
Fred's suggestions have been resolved.

2024-09-05 13:44 UTC, mainegra approved these changes

2024-10-09 14:33 UTC, rtownson commented
Closing this because it's superseded by #1197.

2024-10-09 14:56 UTC, ftessier approved these changes

2024-10-09 14:57 UTC, closed without merging