Integrate ESTAR density effect corrections into EGSnrc
nrc-cnrc/EGSnrc pull request #888
Opened 2022-07-05 17:27 UTC by rtownson

The ESTAR fortran code from NIST has been translated into C++ and integrated into EGSnrc, so that density effect corrections are now calculated on-the-fly during the initialization of a simulation. Materials can be defined directly in the input file, so .pegs4dat and .density (density correction files) are no longer needed.

Example:
```
:start media definition:
  :start water:
    elements = H, O
    number of atoms = 2, 1
    rho = 1.0 # g/cm^3
    ivalue = 75 # eV, optional
  :stop water:
:stop media definition:
```

Thanks to our co-op student @Sehmimul for this significant contribution!

2022-07-05 21:31 UTC, ftessier commented
This will be merged in `develop` after 2022 release.

2022-07-06 11:58 UTC, ftessier commented
Is there an option in the integrated estar code to compute density corrections for a density that is different from the bulk density, e.g., for the grain density in graphite?

2022-07-06 17:12 UTC, rtownson commented
I'm also planning to change the I-value to be specified in MeV, like all other energy parameters..

2023-08-08 19:06 UTC, ftessier commented
@rtownson What is the status of this draft? Should I start working on this branch towards merging, or should I hold off?

2023-08-08 19:10 UTC, rtownson commented
I think hold off, I'm planning to add a few more features.

2023-08-08 20:32 UTC, ftessier commented
Sounds good. I will start reviewing and "cleaning" it on the side, please add stuff on top of the existing `estar-cpp-integration` f21697d, so that I can integrate your new commits cleanly at the end. Don't forget to update to f21697d, I synced it with `develop` last week.

2024-05-16 19:55 UTC, rtownson commented
Currently the `gas pressure` is applied only when a density correction file is not used. It has only one line of action, in the `subroutine MIX` which "calculates MS parameters", it modifies the density:

```
IF (GASPP.NE.0.0) [RHOP=GASPP*RHOP;]
```

Is there a reason that the density itself is not just immediately modified after arguments are read in? For the ESTAR implementation, this would mean that the density change from gas pressure is *not* considered in the density corrections (just like it is ignored when you use a density correction file). Since a user can just modify the density directly in-line, why have the gas pressure separated?

2024-10-03 18:49 UTC, rtownson commented
There seems to be an outstanding bug where `elements` input with 2 letters (e.g. `Al`) results in a crash. Mixture compounds with 2 letter elements work fine.

2024-11-19 20:16 UTC, rtownson commented
> There seems to be an outstanding bug where `elements` input with 2 letters (e.g. `Al`) results in a crash. Mixture compounds with 2 letter elements work fine.

I'm guessing this is fixed by #1182

2024-11-22 00:42 UTC, blakewalters commented
@rtownson, I think so.

2026-01-28 22:54 UTC, mainegra commented
@rtownson I have been testing this PR and been having issues defining **individual elements** such as Al, Ir, or Cu:

```
== MEDIUM 3 BLOCK FOR ESTAR ==
Formula is IR with fraction 192.2
Incorrect formula

***************
You have mistyped the element name or have an element whose atomic number is more than 100
***************

-------------------------
== MEDIUM 10 BLOCK FOR ESTAR ==
Formula is AL with fraction 26.9815
Incorrect formula

***************
You have mistyped the element name or have an element whose atomic number is more than 100
***************

```
This also happens for compounds with elements with two characters such as HCl:

```
== MEDIUM 7 BLOCK FOR ESTAR ==
Formula is H with fraction 1.00797
Formula is CL with fraction 35.453

The medium 7 is a compound with formula: H1

For medium 7 I-value (eV) given in egsinp file is 75

Density correction factors have been calculated by ESTAR for medium 7.
Writing density correction file: 'chloridic_acid-egs-estar.out'
-------------------------
```

But in this case `Cl` gets simply ignored!

If I use the option to declare them as mixtures, then it works!
Note that for single letter elements this also works!

I am also evaluating the impact of observed differences with EGSnrc default density corrections. I'll keep you posted!

2026-01-31 19:40 UTC, rtownson commented
@mainegra I believe I've fixed the bug for compounds containing elements with two character names (like Cl). Note that this solves a different issue than https://github.com/nrc-cnrc/EGSnrc/pull/1182.

2026-02-16 15:53 UTC, mainegra commented
@rtownson as I continue reviewing I "discovered" that the inputs for elements and mass fractions MUST be comma-separated. In other parts of the EGSnrc input files this is not the case. One can use spaces, or commas. This should be made clear somewhere in the documentation or input examples, or ...? 
When passing mass fractions separated by spaces, the code crashes. That is not too bad. But when the elements are entered with spaces, the first one is taken, and no error or warning is issued. This could lead to serious mistakes is a user is not aware of this! ;-)
I am commenting on this right here since I am sure I will forget soon ... ;-P

2026-03-02 18:56 UTC, rtownson commented
> @rtownson as I continue reviewing I "discovered" that the inputs for elements and mass fractions MUST be comma-separated. In other parts of the EGSnrc input files this is not the case. One can use spaces, or commas. This should be made clear somewhere in the documentation or input examples, or ...? When passing mass fractions separated by spaces, the code crashes. That is not too bad. But when the elements are entered with spaces, the first one is taken, and no error or warning is issued. This could lead to serious mistakes is a user is not aware of this! ;-) I am commenting on this right here since I am sure I will forget soon ... ;-P

I can't easily fix this, because the input parsing is done in Mortran. All Mortran list inputs are comma separated, and I can't just add in space-separated lists because it would break inputs like `Atomic relaxations= On in Regions`.  So I'll add a warning to the documentation instead.

2026-03-06 15:14 UTC, mainegra approved these changes
This is a welcome addition to the system! It was painful dealing with external density correction files!

I have tested the effect on two different ionization chambers and found at most 0.1% differences in cavity dose:

Exradin A1SL:

<img width="1619" height="383" alt="Image" src="https://github.com/user-attachments/assets/9761c1ab-8ac4-4e0d-acc8-929b6c9cde24" />

NE2571:

<img width="904" height="104" alt="Image" src="https://github.com/user-attachments/assets/e7ea0452-65c5-445d-a69b-cc585b87858c" />

<br><br>
A more thorough analysis of the effect of density effect corrections might be a useful endeavor! :wink:

2026-03-17 14:34 UTC, ftessier commented
There are about 60 ratios that are unguarded against division by zero in this pr. It would be prudent to review and guard where needed?

```bash
> rg -c '[^/]/[^/0123456789*]' --glob '*.cpp' --glob '*.h'

estarMainCalc.cpp:31
modules/parseDataFile.cpp:1
modules/parse.cpp:3
modules/bisec.cpp:2
modules/datatables.h:2
modules/solverHelpers/cutoff.cpp:2
modules/routine/scof.cpp:5
modules/routine/mixformula.cpp:4
modules/routine/formula_calculation.cpp:1
modules/routine/formulaStruct.cpp:3
modules/routine/formula.cpp:14
```

2026-03-17 15:23 UTC, ftessier commented
@rtownson this is going to be a big one. Don't hesitate to start working on my comments and pushing new commits to update the pr accordingly. Please don't force push yet though. I will clean up the branch at the end.

2026-03-17 17:44 UTC, ftessier requested changes

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/src/pegs4_routines.mortran
> +"I-value is provided in MeV in the egsinp so we need to convert it"
I am unsure about this. I can see that it would be consistent with other energy inputs, however the mean excitation energy I-value is always quoted in eV, as far as I know (e.g., in ICRU Report 90, ESTAR). Opinions?

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.h
> +#include "formula.cpp"
The header should not include the source code. We have to remove this anti-pattern.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.cpp
> +        assert(atomic_number_element > 0);
The `assert` here will just exit without any error code. Although there is information printed just above, we should follow the egsFatal failure mode for consistency. There are five `assert` in this pr, I will review and change to egsFatal.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.cpp
> +    atomic_num = per_table[elem_name];
The `atomic_num` will be set to zero if `elem_name` is not found in `per_table`. Perhaps `atom_num = 0` will be caught later on, but this function should be tight.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.cpp
> +    atomic_num = per_table[elem_name];
```c++
atomic_num = per_table[elem_name];
if (atomic_num <= 0) {
    egsFatal("ESTAR: unrecognized element '%s' in formula '%s' -- "
             "element names must be symbols (e.g. 'C', 'Na'), not integers\n",
             elem_name.c_str(), elemName.c_str());
}
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.cpp
> +        assert(atomic_number_element > 0);
Oh, well now that we guarded against `atom_num()` returning an invalid atomic number, we can remove the guarding here, just delete the `if (atomic_number_element<=0) {` block and the assert.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.cpp
> +        nz[i] = pf.num_arr[i];
Potential buffer overflow? The `nz` array is hard-coded to contain 100 elements, but `mmax` as the loop upper bound is never guarded to be less or equal to 100.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.cpp
> +    int mmax = pf.elem_types;
Add buffer overflow guard on `mmax` index for array `nz` below the `mmax` assignment.

```c++
int mmax = pf.elem_types;
if (mmax > numElemsPerTable) {
    egsFatal("ESTAR: formula '%s' contains %d element types, maximum is %d\n",
             elemName.c_str(), mmax, numElemsPerTable);
}
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.cpp
> +        fc.wt[m] = atb[jm-1]*(nz[m]/asum);
Do we need to guard `asum == 0`?

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.cpp
> +    fc.pot = exp(potl/fc.zav); // we remove the log in equation 5.3 (ICRU 37) and divide by <Z/a> TO GET THE I-value
Do we need to guard `fc.zcav == 0`? This will crash is `parse()` returns `elem_types = 0`.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.cpp
> +        double jm_temp = fc.jz[m]; // we just define jm_temp as a double
This is unnecessary! the `atb` denominator is already a double, and declaring `jm_temp` implies there is a subtlety about precision, but there is none. Remove and just use `jm`.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.cpp
> +    double rhocut = 0.1;
This is a hard-coded value which is somewhat arbitrary. It deserves a named constant, or at least an explanatory comment. Something like:

`// g/cm^3 threshold below which a material is treated as a gas for I-value selection`

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula.cpp
> +    double rhocut = 0.1;
I checked the rest of the files in `estar/`, and there are only 3 instances of the string `0.1`: one here and 2 other legit cases!

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/parse.h
> +#include "parse.cpp"
This anti-pattern has to be removed.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/parse.cpp
> +            if (islower(str[i+1]) != 0) {
Out of bounds if `i == str_len-1`, seems this can happen with compounds, e.g. `NaO`

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/parse.cpp
> +            if (islower(str[i+1]) != 0) {
Could be fixed by dropping in something like:

```
if (i+1 < str_len && islower(str[i+1]) != 0) {
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/parse.cpp
> +            assert(error_handler==0);
Change to `egsFatal` graceful termination instead of `assert()`.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/parse.cpp
> +        if (isdigit(str[i]) != 0) {   // means str[i] is a digit
Index `i` is modified above, so it could fall out of bounds here, add guard.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/parse.cpp
> +            pf.num_arr[j] = val;
Here and a couple lines below, `pf.num_arr` is not guarded against an out of bounds index `j`. Could add something above line 89, like:

```c++
if (j >= 100) {
    egsFatal("ESTAR: formula '%s' exceeds maximum of 100 element types\n",
             str.c_str());
}
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/parse.cpp
> +            pf.num_arr[j] = val;
The `val` integer is not guarded against `val == 0`, e.g. if the input is `H0O` This will corrupt the calculation, probably silently. Easy to guard:

```c++
if (val == 0) {
    egsFatal("ESTAR: zero atom count in formula '%s'\n", str.c_str());
}
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/parse.cpp
> +            pf.num_arr[j] = val;
I guess we should guard against an upper bound as well for `val`, maybe against an unreasonably large integers like `999` to prevent pathological inputs such as `H2000000`?

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/parse.cpp
> +        if (isupper(str[i]) != 0) { // means str[i] is uppercase
The argument for `isupper()`, `islower()` and `isdigit()` should be cast to `unsigned char` explicitly.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/parse.cpp
> +                val = 1*(49-48) + 10*(50-48)
Replace `48` with `'0'` for clarity (!) and adjust comment.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/parse.cpp
> +            while (p>=0) {
This loop is a hand-rolled version of `std::stoi`! Convert to the idiomatic 

```
pf.num_arr[j] = std::stoi(str.substr(digit_start, i - digit_start));
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +#include "estarMainCalc.cpp"
Remove anti-pattern, only include header files.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +            assert(components.size() >= NEP);
Change this `assert()` (and preceding if clause) to a graceful `egsFatal` exit path, such as:

```
if(components.size() < NEP) {
    cout << "Error: List of elements is inconsistent...\n";
    assert(components.size() >= NEP);
}
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +            assert(components.size() >= NEP);
Also, `NEP` is an integer, but `.size()` returns a `size_t` (unsigned). Could cast this defensively:

```
(int)components.size() < NEP
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +    string estarFormulaArrayInput[nepInt];
Use a `std::vector` here for `estarFormulaArrayInput` and `estarWeightArrayInput`.

Variable-length arrays on the stack are not standard C++. Corrupted data can overflow the stack.

Also review similar arrays in `compoundstoelements_` further down.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +    int nepInt = *NEP;
pointers `*NEP` and `*ISCOMP` are not checked before use! We should at least guard agains `<= 0` indices.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +                components[k][0] = std::toupper(components[k][0]);
Explicitly cast argument to `unsigned char` in `toupper` and `tolower`. As in:

```
components[k][0] = std::toupper((unsigned char)components[k][0]);
components[k][1] = std::tolower((unsigned char)components[k][1]);
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +                components[k][0] = std::toupper(components[k][0]);
Also, a single-letter element which is entered lowercase will not be normalized. Is the intent the following instead?

```
components[k][0] = std::toupper((unsigned char)components[k][0]);
if(components[k].size() > 1) {
    components[k][1] = std::tolower((unsigned char)components[k][1]);
}
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +                    elementStr[charPos++] = ch;
`*elementStr` is a raw char pointer from Fortran of unknown size. With up to 100 elements each padded to 50 chars, `charPos` can reach 5000. If Fortran allocated less, this is a buffer overflow. The size of `elementStr` should be passed in as a parameter and `charPos` guarded accordingly.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +        for (auto it = per_table.begin(); it != per_table.end(); ++it) {
This is an $\mathcal{O}(n)$ lookup every time. A reverse lookup table would be more efficient, but at 100 elements it is probably not worth the trouble...

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +    double rho = 1; // Material density not actually needed, so use a dummy
Fine, but does it trigger any side effect in terms of `rhocut` elsewhere, e.g. triggering the solid phase for a gas, inadvertently?

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.h
> +#include "bisec.cpp"
This anti-pattern has to be removed.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +            del = objective_function(tau, f, eps, nmax, x_mid) ;
`del` can be negative here, as it is assigned the raw return value of `objective_function`. When `x_mid` overshoots the root, `obj_func` is negative, then `del` is negative, hence `del > tolerance` is false, and the loop exits with a very poor approximation! We should be using the absolute value here:

```
del = fabs(objective_function(tau, f, eps, nmax, x_mid));
```

Also, I notice that input parameters to this function are not guarded, e.g. `tolerance` is never guarded against negative or zero values (it should be strictly be positive and well above the float epsilon).

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +            del = objective_function(tau, f, eps, nmax, x_mid);
Same comment as in the other while loop above.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +    double x_mid;
Compilers may complain that `x_mid` is not initialized (although it is in the conditional branches. Why not initialize defensively here?

```
double x_mid = (lowerbound + upperbound) / 2;
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +        cout << "The lower and upper bounds are wrong\n";
Use a proper `egsFatal` call here, something like

```
egsFatal("ESTAR: bisection bounds [%g, %g] do not bracket the root\n",
         lowerbound, upperbound);
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +    for (int i = 0; i < nmax; i++) {
There is no guard on `nmax` being greater than the hard-coded arrays size 1000 for `f[]` and `eps[]`.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +        yql = yql + f[i]/(eps[i]+x);
Hard to predict if the denominator is 0, because we could have `eps[i] = -x` fortuitously. This should be guarded with something like a minimum bound on the relative error:

```
double denom = eps[i] + x;
if (fabs(denom) < 1e-10 * (fabs(eps[i]) + fabs(x))) {
    egsFatal("ESTAR: near-zero denominator in objective function "
             "at i=%d, eps=%g, x=%g\n", i, eps[i], x);
}
yql = yql + f[i] / denom;
```

Cannot use the `epsilon` from `egs_functions.h` here, it is too small!

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +    yql = log(1/yql);
Guard against negative argument for the log function, as in:

```
if (yql <= 0) {
    egsFatal("ESTAR: non-positive argument to log in objective function: yql=%g\n", yql);
}
yql = log(1/yql);
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +    yl = log(tau*(tau+2.0));
Guard against negative argument to log function, as in:

```
if (tau <= 0) {
    egsFatal("ESTAR: non-positive tau=%g passed to objective function\n", tau);
}
yl = log(tau*(tau+2.0));
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +    if ((objective_function(tau, f, eps, nmax, lowerbound) > 0) && (objective_function(tau, f, eps, nmax, upperbound) < 0)) {
I would clarify:

```
double f_lower = objective_function(..., lowerbound);
double f_upper = objective_function(..., upperbound);
if ((f_lower > 0) && (f_upper < 0))
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +            if (objective_function(tau, f, eps, nmax, x_mid) > 0) {
The `objective_function` can be called a single time per iteration here. Same for the while loop in the other branch of the conditional. This also clarifies the intent:

```
double f_mid = objective_function(..., x_mid);
if (f_mid > 0) {
    lowerbound = x_mid;
}
else {
    upperbound = x_mid;
}
del = fabs(f_mid);
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +double bisec(double lowerbound, double upperbound, double tolerance, double tau, double f[1000], double eps[1000], int nmax) {
Add a guard on `tolerance`, because a negative or zero value will lead to an infinite loop. Consider:

```
if (tolerance <= 0) {
    egsFatal("ESTAR: bisection tolerance must be positive, got %g\n", tolerance);
}
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +double bisec(double lowerbound, double upperbound, double tolerance, double tau, double f[1000], double eps[1000], int nmax) {
Also, the condition `lowerbound >= upperbound` is never assessed, but would guard against silent nonsensical results. Consider:

```
if (lowerbound >= upperbound) {
    egsFatal("ESTAR: bisection requires lowerbound < upperbound, got [%g, %g]\n",
             lowerbound, upperbound);
}
```

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/estar/modules/bisec.cpp
> +double yl;
Global variables `yl`, `yql` and `obj_func` are only used inside `objective_function`. They serve no purpose as globals but are not thread-safe! They should simply be local variables inside `objective_function`.

2026-03-17 17:44 UTC, ftessier commented on HEN_HOUSE/specs/egspp1.spec
> +estar_advanced_application_files = $(ESTAR_DIR)estarPreProcess.cpp \
I am not sure this is the right way to include the estar functionality. Let's consider **compiling it as a library instead,** just like `iaea_phsp` is included!

2026-03-17 23:12 UTC, ftessier commented
This pull request requires many many changes. Most of them fall under _code hygiene_ (guards, namespace, looping constructs, out of bounds). But there are a few real bugs in there! I am first adding all the comments, and then implement the changes.

Also needs at the end:

- [x] Branch cleanup
- [ ] An `astyle` coding style pass
- [ ] Decision on how to insert in EGSnrc (module or within egs++)?
- [ ] Acknowledge contribution of original estar code
- [ ] Add standard EGSnrc file header in every file
- [ ] Check authorship and contributors in each modified file

2026-03-18 01:44 UTC, ftessier commented
@rtownson, I am done with my review. I will implement the simple one on additional commit on top of this pr, and resolve the corresponding conversations. Feel free to handle some of them too, if you want. 😃

2026-03-18 01:46 UTC, ftessier commented
The question remains: do we want to integrate this within EGSnrc, e.g. using calls such as `egsFatal()`, etc.? Or should it be an indpendent module (a bit like `iaea_phsp`) which can be used independently, and linked to EGSnrc as a library?

2026-03-18 01:48 UTC, ftessier commented
We have to add the standard EGSnrc file header in every file, and probably clean up the file names etc., and acknowledge that this a reimplementation (and improvement) of the original estar program.

2026-03-18 02:00 UTC, ftessier requested changes

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/datatables.h
> +using namespace std;
Must remove `using namespace std;` in headers, because it pollutes the namespace of every translation unit that would include the header. Use `std::` throughout the code instead. I think here there is a single change required from `map` to `std::map`.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/datatables.h
> +double er[] = {1.00e-03,1.25e-03,1.50e-03,1.75e-03,2.00e-03,2.50e-03,
Variables are not only declared here, they are instantiated in the header! This will lead to multiple colliding definitions if this file is ever included elsewhere, which it might very well be given the generically useful data it contains. Here it works because only `estarMainCalc.cpp` is including this header.

The usual way to do resolve this is to declare the variables as `extern` in the header, and define them in the accompanying `.cpp` file (would have to be created in this case).

Another option is to use the `inline` decorator, but I think it is only possible to inline variables with c++ version 17 and beyond.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/datatables.h
> +double atb[] = {1.007940,       4.0026020,      6.9410,         9.0121820,
All variables should be `const` here, I don't think these arrays are ever modified. Declaring them constant will perhaps boost optimization.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/datatables.h
> +// atomic numbers 1 -98 were included (source: https://physics.nist.gov/PhysRefData/Star/Text/method.html).
Unfortunate space in `1 -98`, it should read `1 to 98` for perfect clarity. Same comment for `1 - 100` above, just write it as `1 to 100`.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/datatables.h
> +map<string, int>per_table =     {{"H", 1}, {"He", 2}, {"Li",3}, {"Be",4},
I don't like the obscure `per_table` array name, let's change it to something more evocative like `element_Z` or just `atomic_number`. There are only a handful of instance throughout all files under `estar/`.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/datatables.h
> +// * I-val of graphite in (ICRU 37 - table 4.3) is 78 eV. However in ESTAR 81 eV is used (poth[5]).
Should we be referencing ICRU 90 for water and graphite values? Also, the chlorine I-value comment is hanging. Is this a deliberate change, is this an improvement? Is this related to the gaseous phase? So many questions 😄

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/datatables.h
> +double er[] = {1.00e-03,1.25e-03,1.50e-03,1.75e-03,2.00e-03,2.50e-03,
Let's put some semantics in variable names! I propose `energy_grid[]` here, instead of the obscure `er[]`. There are only 4 instances to update, including this one.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/elementData.h
> +double elementData[14532] = {
Same issue as noted in `datatables.h`. The variable should be declared here `extern`, but defined in an accompanying `.cpp` file. Or if we are entirely committed to c++ version 17 and beyond, we can just add the `inline` decorator here. Again, it compiles fine in this case because it is only included once.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/elementData.h
> +    1,113
We need a clear explanation of the data structure here in a header comment. This is a serialization of the the estar data, something like the following (not sure this is entirely accurate, needs review!):

```
// elementData[] encodes ESTAR density-effect correction data for elements with atomic numbers Z from 1 to 100.
// The array is a flat sequence of per-element blocks with the following layout:
//
//   <nshells>, 113          — number of subshells; energy grid size (always 113)
//   <Z>                     — atomic number
//   <I>, [oscillator...]    — mean excitation energy in eV; for heavier elements
//                             (roughly Z > 10), additional oscillator-strength
//                             parameters follow
//   [nj...], <-sentinel>    — subshell occupation counts, terminated by a negative
//                             value sentinel (heavier elements only)
//   [Ej...]                 — subshell binding energies in eV (heavier elements only)
//   <delta[0..112]>         — 113 density-effect correction values on the fixed
//                             energy grid defined in er[]
//
// See parseDataFile.cpp for the exact parsing logic, and ICRU Report 37 for the
// underlying physics.
```

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/elementData.h
> +double elementData[14532] = {
Hard-coded magic values. There should be a comment about the origin of this number, which is probably just derived from whatever size the array came to when it was computed. There is no clear pattern because the number of items per element varies.

(We really have to convert these flat arrays to structured data, but that is for another day...)

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/parseDataFile.h
> +#include "parseDataFile.cpp"
Remove this anti-pattern inclusion of a `.cpp` file in a header.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/parseDataFile.cpp
> +using namespace std;
Avoid `using namespace std;`. Use the `std::` prefix everywhere instead, for consistency and to avoid namespace collisions.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/parseDataFile.h
> +struct data;
add `extern` decorator: the data struct is defined in the `.cpp` file.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/parseDataFile.cpp
> +    double arr[14532];
Why a full copy of the `elementData` array? this is not required since `arr[]` is only read, never written. This is sitting at 14532 $\times$ 8 bytes = 116 kB on the stack! Read directly from `elementData` (and make it `const` for peace of mind).

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/parseDataFile.cpp
> +        ds.nmax[i] = temp_nmax[i];
I am confused here. The comment says that `rlos_temp` is input in the structure, but the array is never read!?? Does this mean that the 113 density-effect correction values are just dropped and never actually used? I don't see any other reference to `elementData[]` under `estar/`, what am I missing?

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/parseDataFile.cpp
> +            rlos_temp[a] = arr[n]; // the remaining 113 numbers in each set is stored in rlos_temp array
These are set but never used.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/parseDataFile.cpp
> +        int k = j+2; // the second element of each set of data is 113 and thus we ignore the second element
This assumption that all elements are on a 133-point grid is fragile. Let's guard it more diligently:

```c++
if (elementData[j+1] != 113) {
    egsFatal("ESTAR parseDataFile: element %d has grid size %d, expected 113\n",
             i+1, (int)elementData[j+1]);
}
```

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/parseDataFile.cpp
> +    int nc_temp[26];
There are no bound guards on `nmax`, `nc_temp` and `bd_temp` throughout. One could use a zero-cost `static_assert()` for these bounds, since the array sizes are hard-coded.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/parseDataFile.cpp
> +        while (k < j + 2 + temp_nmax[i]) {
Convert to for-loop for clarity and better auditing.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/parseDataFile.cpp
> +        while (n < m + ds.numLevelsStandard) {
Convert to for-loop for clarity and better auditing.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/parseDataFile.cpp
> +        while (m < k + temp_nmax[i]) {
Convert to for-loop for clarity and better auditing.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/bspol.h
> +#include "bspol.cpp"
Remove anti-pattern inclusion of `.cpp` file in header.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/bspol.cpp
> +using namespace std;
Avoid `using namespace std;`, just use prefix `std::` where it is required.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/bspol.cpp
> +bspol fbspol(double s, double x[1000], double a[1000], double b[1000], double c[1000],double d[1000], int n) {
This seems to be a second implementation of the bisection method in `bisec.cpp`. Is it possible to maintain a single implementation in `bisec` and call it from the `bspol` interpolation?

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/bspol.cpp
> +bspol fbspol(double s, double x[1000], double a[1000], double b[1000], double c[1000],double d[1000], int n) {
The `[1000]` array size in the function parameters, because array parameters decay to pointers anyways in c++. It is just misleading. What matters is the parameter `n`, so the `[1000]` indications are misleading. Just use `*x`, `*a`, etc. Ideally this would all be refactored to use `std::vector` instead.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/bspol.cpp
> +        int binary_temp = 0; // we define binary_temp = 0 as the loop must run at least once
Convoluted, just use a `do...while` loop instead, remove the `binary_temp` flag!

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/bspol.cpp
> +        while (abs(mu-ml)>1 || binary_temp==0) {
the `abs()` from <math.h> operates on doubles. Use `std::abs()` for intergers instead (another good reason to avoid `use namespace std;` 😉).

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/bspol.cpp
> +    if (s>=x[mub+idir-1]) {
This conditional path silently extrapolates beyond the grid boundaries. Maybe this is worth a warning.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formulaStruct.cpp
> +using namespace std;
This is just a struct, the declaration should be moved to `formulaCalculations.h`.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formulaCalculations.h
> +
The `struct formula_calc` should be declared here (and the file `formulaStruct.cpp` entirely removed!)

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +using namespace std;
Avoid `std` namespace, use `std::` prefix instead for clarity.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +#include "formulaStruct.cpp"
Include file `formulaCalculations.h`, which should contain the struct currently defined in `formulaStruct.cpp` (which should then be removed entirely).

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +#include <iostream>
Call this `.cpp` file `formulaCalculations.h` for consistency with other file names and the header base name.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formulaStruct.cpp
> +    double wt[200];
Avoid hard-coded array sizes, or else comment on why `200` is chosen here.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +    if (knmat == 0) {
The parameter `knmat` is supplied, but the branching selector values {0, 1, else} are not explained. It is important to document what these mean.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +            elemPresent[j] = 0.0;
Redundant initialization, remove the `0.0` one, `elemPresent[]` is an int array.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +        int atomicNumArray[NEP];
Array is initialized with a variable which is unknown at compile time. This is what's called a c99 variable-length array, and is not supported in c++ 11 and beyond. Use `std::vector<int>` instead.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +        cout << "\n";
There are 6 `cout` expressions in this file, consider replacing with `egsInformation()` calls.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +        float finalNumAtoms[100]; // array containing the number of atoms of each element present
The `finalNumAtoms[]` array should be `int`, unless we store fractional number of atoms in some context?

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +    RestructureCompound compRes(string *inputElemArray, float *inputNumAtomArray, int NEP) {
The `inputNumAtomArray` should be `*int` here, no?

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +        while (i < NEP) {
Convert to for-loop.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +        while (m < perTableLength) {
Convert to for-loop.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +        while (i < NEP) {
Convert to for-loop;

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +            atomicNumArray[i] = per_table[inputElemArray[i]];
This probably needs guards on `i`, and perhaps on `inputElemArray[i]`. An unrecognized symbol silently returns 0, giving atomicNumArray[i] = 0 and then zIndex = -1, which is out of bounds.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/formulaCalculations.h
> +formula_calc getDataFromFormulae(int knmat, double rho, string *elementArray, double *massFraction, float *numOfAtoms, int NEP);
Missing the `mediaNum` parameter compared to the signature in the `.cpp` implementation.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +using namespace std;
Avoid `std` namespace, use `std::` instead.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.h
> +#include "mixformula.cpp"
Remove anti-pattern, include `.h` file in `.cpp` file instead.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +int const max_comp = 100;
A comment seems in order here about this hard-coded value choice.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +    cout << "how many components? ";
Consider removing  all `cout` calls with `egsInformation()` ones.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +    while (i < ncomp) {
Replace with a for-loop.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +    while (i < ncomp) {
Replace with a for-loop.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +    while (i < ncomp) {
Replace with a for-loop.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +    while (j < num_elems) {
Replace with for-loop.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +mixtureData getData() {
Remove dead code `getData()`?

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.h
> +mixtureData getData();
`getData()` seems to be dead code.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +        assert(ncomp >= 0);
Assertion seems to be backwards? At any rate, replace with a more graceful `egsFatal()` call.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +            assert(massFraction[i] > 0);
This will never trigger, seems to be backwards. At any rate, replace with more graceful `egsFatal()` exit.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +        fc = fcalc(2, rho, formulaArray[i]);
Opaque value for `knmat` parameter, worth a comment.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +    string estarFormulaArrayInput[numCompounds];
A number of c99-style variable length arrays, this is not standard c++. Replace all with `std::vector`;

```c++
string formulaArray[numComp];
double fractionArray[numComp];
double zavArray[numComp];
double potArray[numComp];
```

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +    double lh[num_elems];
The array `lh[]` is used as flag and as a sentinel, as far as I can see. should be `bool` or `int`.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +    int ncomp = NEP;
No guard for upper loop bound `ncomp`, set to the `NEP` parameter.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +        cout << "\n***************\n";
Replace with more graceful `egsFatal()` call.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/mixformula.cpp
> +    double fractionArray[numComp]; // srray contaning all the weights
Typo: `array` instead of `srray`.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/scof.h
> +#include "scof.cpp"
Resolve anti-pattern of including `.cpp` file in header.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/scof.cpp
> +    double a[1200];
Array size mismatch with `bspol` files (they use 1000).

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/scof.cpp
> +    int m2 = nmax-1;
Need a guard on `nmax` parameter which is used as an array index.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/scof.cpp
> +        r = (f[m+1] - f[m])/sf.d[m];
Not guarded against division by zero. I don't think that `x[m+1] != x[m]` is guaranteed here. Would crash if successive coordinates are identical.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/scof.cpp
> +        r = s/sf.b[m];
Not guarded against division by zero. Same comment 4 lines down.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/scof.cpp
> +    for (int m = 0; m < m2; m++) {
Review guards for division by zero in this loop.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/scof.cpp
> +#include <math.h>
Include `<math.h>` is not used in this `.cpp` file. Remove.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/scof.cpp
> +using namespace std;
Avoid `std` namespace, use explicit `std::` prefix when needed.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/routine/scof.h
> +scof fscof(int nmax, double x[1200], double f[1200]);
Use `*x` in function signature, the `[1200]` is transparently ignored and thus misleading.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/solverHelpers/headerfile.h
> +class HelperFunctions {
This file name is too generic. Change it to `cutoff.h` since it only declares the `cutoff()` function defined in `cutoff.cpp`

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/solverHelpers/cutoff.cpp
> +    if (en[nmax-1] <= 0) {
Guard parameter `nmax`, which is used as an array index and for loop termination.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/solverHelpers/cutoff.cpp
> +            sum = sum + f[n]/eps[n];
Guard against division by zero.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/solverHelpers/cutoff.cpp
> +        ycut = 1/sum;
Guard against division by zero.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/solverHelpers/headerfile.h
> +    double cutoff(double *, double *, double *, int);
Add parameter names in declaration, not strictly required but best practice.

```
double cutoff(double *en, double *eps, double *f, int nmax);
```

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/solverHelpers/cutoff.cpp
> +using namespace std;
Avoid using `std` namespace, use `std::` prefix instead.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/solverHelpers/cutoff.cpp
> +#include <math.h>
Remove unused `<math.h>`.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/solverHelpers/cutoff.cpp
> +    // here we computer cutoff below which density effect is 0. However this cutoff is not used in estar.
It would be good to flesh out a little bit why this cutoff is not used anymore. I am in favour or removing dead code, unless there is a good reason to keep it around? I don't see anything in "section 4" of the ICRU Report 37 that pertains to this threshold not being used anymore. Section 6 explains why there is no cutoff for metals (valence electrons are in the conduction band), but there is a minimum energy for insulator, for which the density effect applies). But the comment a few lines down again specifies that `ycut` is not used in estar.

I cannot find any discussion of the removal of this cutoff in ICRU Report 90 either.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/solverHelpers/cutoff.cpp
> +    // here we computer cutoff below which density effect is 0. However this cutoff is not used in estar.
@rtownson, perhaps the author is referring to a report he has written on this estar project?

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/solverHelpers/cutoff.cpp
> +    // here we computer cutoff below which density effect is 0. However this cutoff is not used in estar.
A [talk by Matthew Strait](https://indico.cern.ch/event/825436/contributions/3487429/attachments/1879446/3096088/densityeffecttalk.pdf) provides illumination 💡 :

- The "exact" computation was given by Sternheimer in 1952 and 1984..
- Owing to computational burden, he proposed as parametrized version in 1971.
- The approximate method relied on $\delta=0$ below some cutoff.
- Since we are using the exact calculation, we don't need this cutoff.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/modules/solverHelpers/cutoff.cpp
> +    // here we computer cutoff below which density effect is 0. However this cutoff is not used in estar.
Suggested source code comment _before_ removing cutoff.cpp and headerfile.h altogether.

```c++
// The density-effect cutoff (the energy below which delta=0) was a feature of
// Sternheimer's parametric approximation (Sternheimer & Peierls, Phys. Rev. B3,
// 3681, 1971), introduced to reduce computational burden. Since EGSnrc uses
// the "exact" Sternheimer method (Sternheimer, Berger & Seltzer, Atom. Data Nucl.
// Data Tabl. 30, 261, 1984), in which delta emerges naturally from the oscillator-
// strength calculation and requires no imposed cutoff, this function is no longer
// needed.
//
// [doi link to Sternheimer & Peierls, Phys. Rev. B3, 3681, 1971]
// [doi link to Sternheimer, Berger & Seltzer, Atom. Data Nucl. Data Tabl. 30, 261, 1984]
```

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarMainCalc.cpp
> +using namespace std;
Avoid using `std` namespace, use the `std::` prefix instead.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarMainCalc.cpp
> +#include "modules/solverHelpers/cutoff.cpp"
We are removing `cutoff.cpp`, so this will go too!

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarMainCalc.cpp
> +#include <iomanip>
File wide:

- Consider using `egsInformation()`, `egsWarning()`, and `egsFatal()` throughout, instead of `cout` and `assert()`.
- Refactor simple while-loops as for-loops when possible.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarMainCalc.cpp
> +        ds = parseData();
the function `parseData()` (and its scanning 14532 values) on every iteration! Call once before the loop. And as noted in `parseData()` does not actual save the density-effect coorection values anywhere, so I wonder...

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarMainCalc.cpp
> +    while (abs(droot)-0.00001 > 0) {
This has no cap if convergence fails. We need a cap with `egsFatal()` if it is not converging.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarMainCalc.cpp
> +                if (solver == 1) {
Branch is never reached since we set `int solver = 2;` at the outset and it is not modified afterwards. I understand that this is a selector to pick between two options: so it should be refactored as such, so that the estar approximation can be tested anytime.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarMainCalc.cpp
> +        if (iz == 6 and mmax==1) { // elemental carbon is dealt differently
The `and` operator is supported in c++, but it is rarely used, and not at all in this code base. Change to `&&`.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarMainCalc.cpp
> +    int knmat;
Ah! This is where the `knmat` value meanings are explained! Lift this into a named enum with explanation and then use the enum everywhere instead of hard-coded values, for clarity and maintainability.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarMainCalc.cpp
> +#include <iomanip>
Review magic numbers throughout:

- `28.81593`: the plasma frequency coefficient (eV), use a named constant with a ref to Sternheimer 1984.
- `0.510999906`: electron rest mass in MeV, same treatment
- `0.000000001`: Newton's method convergence tolerance, should be named
- `50` for `at[]` and `g[]` arrays: maximum number of element types in a compound? Needs a comment

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarMainCalc.cpp
> +    while (k < fc.mmax) {
type mistmatch: `fc.mmax` is `int` but `k` is `unsigned int`.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/estar/estarMainCalc.cpp
> +        return 9;
Undocumented return value? Define error codes as `const` integers overall and return those.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/pegs4/density_corrections/compounds/calciumcarbonate.density
> + 4.00E-01,7.165E-02  4.50E-01,1.004E-01  5.00E-01,1.302E-01  5.50E-01,1.606E-01
These modifications are at the precision limit, so they are innocuous.

However, the question becomes: why only this file is changed? I presume this one was used in testing and inadvertently added in a commit? I recommend reverting these changes so the estar pr is neutral in terms of the historical density files distributed with EGSnrc. Later on, we may want to recompute _all_ the files, but changes in a single `.density` file here raises concern.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/specs/all_common.spec
> +ESTAR_S_HELPERS = $(ESTAR_MODULES)solverHelpers$(DSEP)
We won't be needing the helpers anymore. Once we remove `cutoff.cpp`, the whole `solverHelpers/` directory goes.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/specs/all_common.spec
> +F77_CPP_LINKER = -lstdc++ -std=c++11
`-std=c++11` is a _compiler_ flag. Harmless here, but misleading. At any rate, we should not have specific flags to compile or link estar. I presume this is a leftover from a time before we moved on to c==14 as the standard?

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/specs/all_common.spec
Might as well fix typo `plarforms` → `platforms` while the file is open.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/makefiles/standard_makefile
> +	@echo "Fortran compiling $(FORTRAN_FILE).$(FEXT) using flags '$(EGS_EXTRA_FLAGS) $(FCFLAGS) $(OPTLEVEL_F)' and extra objects/libs '$(EGS_EXTRA_OBJECTS) $(ESTAR_DIR)estarPreProcess.cpp $(F77_CPP_LINK
It is unusual to pass a `.cpp` file to link directly. Normally one compiles to an object file. Is there a reason here to side step the usual compilation workflow?

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/estar_um.tex
> +The implementation of {\tt ESTAR} density effect corrections in EGSnrc includes improvements over the original software by Sternheimer {\em et al.} \cite{St82}, and these are detailed below.
Consider citing St84 as well (Atom. Data Nucl. Data Tabl. 30, 261, 1984).

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/estar_um.tex
> +\lfoot[{\sffamily {\leftmark}}]{{\small Last edited $Date: 2013/09/26 17:59:27 $
Stale date for "Last edited".

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/estar_um.tex
> +% Beware: Using the macro below conflicts between CVS and latex!!!
Remove ancient CVS warning!

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/estar_um.tex
> +%  Author: Reid Townson
Align as in other EGSnrc file headers.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/doc/src/pirs701-egsnrc/inputs/pegsless_um.tex
> +    :start water:
Second media also called `water`. Might be better to call it something else like `saline` or `salt_water` in case someone copies the two example media together.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/src/pegs4_macros.mortran
Should the new estar code path be noted here in the comment? Perhaps this is out of scope for this pr.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/doc/src/pirs701-egsnrc/pirs701-egsnrc.tex
@rtownson I think you should add your name in the authors here. You are in the [citation](https://github.com/nrc-cnrc/EGSnrc/wiki/Citing-EGSnrc)!

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/doc/src/pirs701-egsnrc/pirs701-egsnrc.tex
Stale dates, ancient CVS warning to remove.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/src/get_media_inputs.mortran
> +        iscompound(i) = 0;
This seems to be only set in the non-compound path, not in the compound (ELSE) branch code path.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/src/pegs4_routines.mortran
> +IF(IPOTVAL > 0.1) [
Some I-values are in the hundreds of keV, so it seems this would trigger too often? Perhaps it should warn when `IPOTVAL > 1.0`?

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/src/pegs4_routines.mortran
> +    enGrid,NCOMPOUNDS,ISCOMP,IEV,IPOTVAL,MEDID,OUTDENSITY);
Here and below, it looks as though the `IEV` is no longer initialized. It was in the code sections that were removed. Needs a check. Same thing in the ELSE branch.

2026-03-18 02:00 UTC, ftessier commented on HEN_HOUSE/src/get_media_inputs.mortran
> +        CALL compoundstoelements(compoundList_tmp, compoundFractions_tmp,
Where is `compoundstoelements()` defined?

2026-03-18 08:55 UTC, ftessier commented
Wait, `estar-cpp-integration` is not the right branch for this pr. I had cleaned the estar branch into `clean-estar-cpp-integration`. I will bring this branch here up to date, only a few diffs (but the history is cleaner!).

2026-03-18 09:14 UTC, ftessier commented
Reset this branch to the `clean-estar-cpp-integration` one. There was no diff between the original pr branch 9b6acde5 and the clean version 3f7255f8. The diff was null at the time of the reset:

```
git diff 9b6acde5 3f7255f8
```

Effectively, the clean branch was in sync with the original pr branch as of commit 00b8b638, so it was only necessary to cherry-pick commits 7ab80fa7..9b6acde5 onto the clean branch to reset to the clean history.

2026-03-24 18:11 UTC, ftessier commented
Rebased on updated `develop` branch, no conflict.

2026-03-24 18:14 UTC, ftessier commented
@rtownson I am merging this in `develop` so that we can use and test it. However, the review comments still need to be addressed, so I will not delete the branch and we will review before the v2026 release.

I have tagged develop with `before-estar-egsview` as the pristine point before integrating estar and egs_view changes that still need review.

2026-03-24 18:16 UTC, merged

2026-03-27 19:51 UTC, mainegra commented
@rtownson how does EGSnrc decide whether to compute density corrections based on ESTAR or using the PEGS4 model (Sternheimer)? Should there be a switch or flag to allow selecting which one to use? The trivial case is when a density correction is provided.

2026-04-22 13:15 UTC, rtownson commented
Note that I'm marking Fred's suggestions as resolved here, as I work on them on a new PR #1396

2026-04-22 17:24 UTC, rtownson commented on HEN_HOUSE/estar/estarPreProcess.cpp
> +    double rho = 1; // Material density not actually needed, so use a dummy
I've made this change to pass along the density for the rhocut gas checks, but it should be tested.

2026-04-22 18:00 UTC, rtownson commented on HEN_HOUSE/estar/modules/datatables.h
> +// * I-val of graphite in (ICRU 37 - table 4.3) is 78 eV. However in ESTAR 81 eV is used (poth[5]).
I added to the comment that the graphite choice is from ICRU 90. For chlorine, the I-value is as it was in the original fortran ESTAR and I don't see a reasoning for it there.

2026-04-22 20:17 UTC, rtownson commented on HEN_HOUSE/estar/modules/routine/formula_calculation.cpp
> +        float finalNumAtoms[100]; // array containing the number of atoms of each element present
It's only used as an int, and it gets casted to that. This ended up happening because the corresponding array in Mortran is of floats, for whatever reason. It traces back to here, though it's copied to `PZP` by the time it gets to estar:

```
pz4(i,j)=rhoz4(i,j)/wa4(i,j);
```

At least in estar, it's only used for compounds and always works out to be integers as far as I can tell. I left the casting to happen on the C++ end to avoid making Mortran modifications.