Add the egs_gammaspec app
nrc-cnrc/EGSnrc pull request #910
Opened 2022-08-11 19:01 UTC by rtownson

Add an application for calculating gamma spectrometry related quantities, like detector efficiency and coincidence summing corrections. It outputs spectra both with coincidence summing effects included (e.g. a realistic or "non-perfect" detector), and without summing effects (a "perfect" detector). Total efficiency and full energy peak efficiency are also calculated for each case.

The `egs_radionuclide_source` was changed slightly to allow for the calculations - it now returns the number of decays from `getNextParticle`, instead of the number of source particles. This does not change the normalization when using the source, but apps specially designed to use `current_case` and `last_case` for the radionuclide source may be affected.

The application specific inputs are:
```
:start scoring options:

    :start output spectrum:
        scoring regions = crystal_no_dead_label

        #minimum energy  = 0.0 # Optional, defaults to 0
        maximum energy = .4 # Optional, defaults to maximum in source

        number of bins  = 2000

        # Example: these are peaks of interest for Ba-133, in MeV
        # Efficiency and coincidence summing corrections will be calculated for each of these
        gamma analysis energies = .0309 .035 .0531 .0796 .0810 .1606 .2232 .2764 .3028 .356 .3838
    :stop output spectrum:

:stop scoring options:
```

2024-06-13 18:03 UTC, blakewalters requested changes
Compiles, runs and seems to produce the desired output, @rtownson!  Just a couple of questions: 1) Would it be useful to have an option to output these efficiencies to a file? and 2) Does this branch need to be rebased on develop before merging?

2024-06-13 18:33 UTC, rtownson commented
I think since the list of efficiencies is usually just a few numbers, it's OK to have it just be in the .egslog file, similar to the dose reported for `egs_chamber`.

Wouldn't be a bad idea to do a more recent rebase before merging.

2024-09-04 19:16 UTC, rtownson commented
There are quite a few people using this branch - it would be nice to review & merge it into the 2024 release.

2024-09-05 13:40 UTC, mainegra approved these changes

2024-09-06 23:02 UTC, blakewalters approved these changes

2024-10-11 15:43 UTC, ftessier approved these changes

2024-10-11 16:43 UTC, merged