Fix egs_cbct compilation and example
nrc-cnrc/EGSnrc pull request #940
Opened 2022-11-24 16:29 UTC by rtownson

Fix a compiler error that occurred with newer compiler settings due to ambiguous declaration of isinf and isnan, by adding `std::`.  

Also change the z-rotation parameter in the example input file to be 0 so that it calculates the first projection instead of a later projection. This avoids a common user error when trying to produce the blank scan for the first time, as reported here: https://www.reddit.com/r/EGSnrc/comments/z36841/query_fatal_error_message_egs_cbct_blank_scan/

2022-12-15 19:47 UTC, mainegra commented
@rtownson thanks for looking into this! My only comment is that in the case of the non-zero rotation, if both, the blank scan and the actual scan use the same rotation, then there should be no issue as the projection would be place at the same location of their corresponding scan files!

2022-12-15 19:49 UTC, mainegra commented
Setting the rotation to 0 will simply show a different phantom scan. So, it really doesn't matter.

2022-12-15 21:14 UTC, mainegra commented
> @rtownson thanks for looking into this! My only comment is that in the case of the non-zero rotation, if both, the blank scan and the actual scan use the same rotation, then there should be no issue as the projection would be place at the same location of their corresponding scan files!

Actually, hold that thought! Something is not right! If I were to implement this now, I would just produce a blank scan whose size has to be Nx*Ny*size(float) since this is the same for any projection. Clearly, the blank scan produced with a non-zero angle makes no sense! So, your recommendation to set it to zero is the correct one! Ideally egs_cbct should not care about projections placement for a blank scan!

2022-12-15 21:24 UTC, mainegra requested changes
Perhaps add to the message reporting blank scan size mismatch a hint to set rotation to zero?

2023-02-16 18:05 UTC, ftessier commented
I will merge this into `master` now because otherwise the `v2023` pre-release does not compile `egs_cbct` nor `egs_fac`!

2023-02-16 18:14 UTC, rtownson commented
Added the egs_fac fixes, now ready to merge.

2023-02-16 18:33 UTC, ftessier approved these changes

2023-02-16 18:38 UTC, ftessier commented
Squashed the 3 commits.

2023-02-16 18:39 UTC, merged