Fix #945, #804: egs_chamber examples don't run by default
nrc-cnrc/EGSnrc pull request #952
Opened 2023-01-09 19:40 UTC by rtownson

Fix the egs_chamber examples so that they now run without needing to compile any BEAMnrc accelerators or make changes to the input file. Also fix a typo in the example2 water box size.

2023-01-09 20:08 UTC, ftessier approved these changes
Nice, thank you!

2023-01-11 19:39 UTC, mainegra approved these changes
Great!

2023-01-13 18:31 UTC, blakewalters requested changes
Looks good, but one thing: When I run example2_chamber_dd, I get a bunch of:
"initScoring: missing/wrong 'sub geometries'  for geometry ..." messages
followed by:
"initScoring: different medium 0 in region 5 compared to medium 2 in region 1 for geometry phsp_scoring_geometry.
Hope you know what you are doing"
And then my run immediately fails with a segmentation fault.  The latter may be a function of my system (using the Mac clang compiler), but what about those warning/error messages?  Are they also due to my system?

2023-01-13 19:32 UTC, rtownson commented
> Looks good, but one thing: When I run example2_chamber_dd, I get a bunch of: "initScoring: missing/wrong 'sub geometries' for geometry ..." messages followed by: "initScoring: different medium 0 in region 5 compared to medium 2 in region 1 for geometry phsp_scoring_geometry. Hope you know what you are doing" And then my run immediately fails with a segmentation fault. The latter may be a function of my system (using the Mac clang compiler), but what about those warning/error messages? Are they also due to my system?

The warnings are normal! The segmentation fault is not.

2023-01-13 19:57 UTC, blakewalters commented
@rtownson, do you know if anyone else gets the segmentation fault on a Mac?  I'll go ahead and change this to an approval, because even if this is a more general issue, it's separate from this.

2023-01-13 19:58 UTC, blakewalters approved these changes

2023-01-13 20:06 UTC, mchamberland commented
> @rtownson, do you know if anyone else gets the segmentation fault on a Mac? I'll go ahead and change this to an approval, because even if this is a Mac-related issue, it would be a separate PR.

I will try reproducing this weekend.

2023-01-15 00:06 UTC, mchamberland commented
> @rtownson, do you know if anyone else gets the segmentation fault on a Mac? I'll go ahead and change this to an approval, because even if this is a Mac-related issue, it would be a separate PR.

@blakewalters @rtownson  Could not reproduce the seg fault on my M2 Mac with the latest GCC toolkit from Homebrew.

2023-01-16 19:07 UTC, ftessier commented
Just trimmed the commit title to fit.

2023-01-16 19:08 UTC, merged